### ISSUE TITLE
Always output `.g.part` files to work around build_runner issue

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/source_gen#369]
See https://github.com/dart-lang/build/issues/1702

Even if the generator throws we should just output the error to the file (I think it used to work this way)?

We should fix this in build_runner but it is probably going to take a while.

**Comment by natebosch** [comment]
It turns out to not be feasible to hack around this. We _are_ outputting a file which contains the error (there's some room to debate whether that is worthwhile...) and the overall build step is failing because of the `log.severe`. There is no space to write out a blank file.

The issue is coming up because when we glob these [filter out failure nodes](https://github.com/dart-lang/build/blob/3ed7bd5c893d5883daa68d8fe387e2ae34978d04/build_runner_core/lib/src/asset/reader.dart#L83) since they are unreadable. We might want to consider that case a failure instead - https://github.com/dart-lang/build/issues/1705

We did consider an even worse hack - change the `log.severe` to a `log.warning` so the build step looks successful, then in `CombiningBuilder` look for a comment like `// Error:` and fail _that_ build step with a `log.severe`. This is an ugly enough hack that it's probably not worth doing.
