### ISSUE TITLE
Generate libraries instead of parts?

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/source_gen#41]
Just curious about the motivation for choosing generated parts instead of libraries.

For hand-written code I generally prefer using `export` to `part`.  It gets rid of all the ugly `_`s and allows one to import or export the sub-libraries elsewhere, such as tests.  Could then either import or export (or both) the generated lib depending on use case.

**Comment by kevmoo** [comment]
@seaneagan great question. The big reason: you can generate and access private "stuff".

For instance, you could access a private constructor for a json factory.

I'm absolutely game to add options for creating helper libraries, too. Just a matter of priority.

**Comment by zoechi** [comment]
I also went with `part of` for my code generation because this is currently the only way to combine generated and hand-crafted code closely (private access) without worrying about overwriting hand-crafted code.
C# added partial classes exactly for this reason AFAIR which goes beyond `part of`, it would be nice to have in Dart as well.

Be able to choose is even better :)

**Comment by jakemac53** [comment]
We now have the `isStandalone` option to `GeneratorBuilder` which allows you to do this.
