### ISSUE TITLE
Allow generators to emit a set of items that can be merged later

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/source_gen#420]
Just hit an issue where two generators generate the same helper – which causes a name conflict.

If they were different things – fine. But in this case they are the same class, so the conflict should just "merge"

**Comment by natebosch** [comment]
If you need this much control you should be implementing with `LibraryBuilder` instead of `PartBuilder`. That's why `LibraryReader` has an `annotatedWith(TypeChecker)` method - so that you can easily reproduce the `GeneratorForAnnotation` behavior yourself while maintaining full control of the output.

**Comment by kevmoo** [comment]
But I still want to generate parts!

**Comment by natebosch** [comment]
`LibraryBuilder` is _usually_ made to write libraries, but I can't think of a reason why it wouldn't be able write part files too - it just won't check the `part of` directive for you.

**Comment by natebosch** [comment]
This is implemented - the return type of `generateForAnnotatedElement` allows returning mutliple Strings (synchronously or asynchronously) and it deduplicates them.
