### ISSUE TITLE
Configuring line length of formatted code

### ISSUE THREAD

**Issue by adamlofts** [dart-lang/source_gen#424]
I am using source_gen via built_value in a project.

In this project we use `dartfmt --line-length 120` as a standard.
The generated code from built_value is using an 80 column line length.

This is causing a fight between the 2 systems where we run dartfmt to format the code but then the builder will change the formatted files back to 80 column lines.

Is there a way to configure the line length of generated code?

**Comment by natebosch** [comment]
Each of `PartBuilder`, `LibraryBuilder`, and `SharedPartBuilder` take an argument `formatOutput` which is a `String Function(String)`. By default this is `DartFormatter().format`. You could pass in instead `DartFormatter(pageWidth=120).format` and I think it'd do what you're looking for.

https://pub.dev/documentation/dart_style/latest/dart_style/DartFormatter-class.html

If you're using `SharedPartBuilder` and there are other parts contributed from other packages, those won't be formatted using these options. We don't have a solution for that.

We don't have plans on making this a `build.yaml` level configuration or similar because we don't expect users to change the line length. That option in the formatter mainly exists for the purposes of testing the formatter.
