### ISSUE TITLE
Question: Is it possible to combine multiple generated codes into a single .g.dart file?

### ISSUE THREAD

**Issue by SaeedMasoumi** [dart-lang/source_gen#429]
I'm using `SharedPartBuilder` to generate some codes for my `@SomeAnnotation`.
But for each dart file, it generates a new `.g.dart` file and if I don't put `part of 'some.g.dart` in the actual source, it gives me a warning that you miss `part of` and it will not generate the codes. 

Here is an example:

```dart
// foo.dart
@SomeAnnotation
class Foo {}
// bar.dart
@SomeAnnotation
class Bar {}
```
What I need is instead of generating `foo.g.dart` and `bar.g.dart`, I want to generate `some_annotation.g.dart` containing both generated codes from `foo` and `bar` without any warning for `missing part of ...`.

Is it possible? I didn't find any documentation for that purpose.

**Comment by jakemac53** [comment]
This is not really supported by `source_gen`, no. You could make a custom builder though which works from application entrypoint files (ie: main.dart) and walks the whole application to find annotations, generating a single part file based on that. For instance `package:reflectable` works like that.

This package expects that each file actually uses the code generated by it directly, and thus it would need to include the generated file as a `part`. In general this is also more conducive to modular compilation - you don't have to re-run the generator for all classes just because one changed, it can invalidate these files individually.

**Comment by natebosch** [comment]
I think what you want is something along the lines of:

- A `LibraryBuilder` to output to `.something_specific.dart`, use `build_to: cache`.
- A custom builder (you can check out `CombiningBuilder` for inspiration) which does a `buildStep.findAssets(Glob('**/*.something_specific.dart'))` and then concatenates all the results to `lib/some_annotation.dart`.

I agree that this isn't something that we want to have specialized in this package.

**Comment by SaeedMasoumi** [comment]
Thank you @natebosch and @jakemac53.
