### ISSUE TITLE
Allow to generate a class by analyzing annotations in class and its fields.

### ISSUE THREAD

**Issue by lukasgarcya** [dart-lang/source_gen#438]
How to generate a class using multiple annotations, such as the example below:

```dart
@Entity
class Todo {

  @Field
  String name;

  @IgnoreFied;
  int calc;

}
```

Generate:

```dart
class Todo extends BaseModel {

  String name;

  Map<String, dynamic> toMap() {
    return {'name': this.name'};
  }
}
```

**Comment by natebosch** [comment]
You can use `GeneratorForAnnotation<Entity>` to target the class.
From there you will have a `ClassElement` (since that is what was annotated with `@Entity()` and you can iterate over the [`fields`](https://pub.dev/documentation/analyzer/latest/dart_element_element/ClassElement/fields.html). You can check for each field to see if it is annotated with either `@Field()` or `@IgnoreField` using [`TypeChecker.hasAnnotationOf`](https://pub.dev/documentation/source_gen/latest/source_gen/TypeChecker/hasAnnotationOf.html).

Closing since I don't think this issue is actionable on this repo.

**Comment by lukasgarcya** [comment]
Referring to this usage could have an example in the repository to save time for anyone looking for. If you want I can make an example because I already understood how to do

**Comment by natebosch** [comment]
Hey @lukasgarcya - I updated the docs to make it a little more clear that `GeneratorForAnnotation` applies to annotated elements at the top level.

I'm a little hesitant to add much more concrete documentation about the analyzer APIs since those aren't defined here...

The updated docs will go live the next time we publish, hopefully they help.
