### ISSUE TITLE
Extension keyword on generated files

### ISSUE THREAD

**Issue by geoffreylzf** [dart-lang/source_gen#440]
Hi, according to Filip on below video
https://www.youtube.com/watch?v=D3j0OSfT9ZI&t=314s

source_gen is able to generate part file with extension keyword, allow developer to write less code.

Is this available now? or how do I need to configure it in order to use the extension?

**Comment by jakemac53** [comment]
`source_gen` doesn't care what type of code you generate, so you don't need to enable or configure anything. This package is just a utility package for generating code it doesn't generate anything on its own.

If you are trying to use some code generator and you would like it to use extensions instead of whatever it is doing today you can file an issue on that code generator.

If you are writing a code generator you just need to make sure you set your sdk dependency to one that supports extensions (>=2.6.0 I believe) and then you can feel free to generate extensions.
