### ISSUE TITLE
File manipulation question

### ISSUE THREAD

**Issue by FilledStacks** [dart-lang/source_gen#508]
I don't know where else to ask this since I can't find the answer on any of the topics. I'm wondering if it's possible to do file manipulation with build or source_gen. 

I just want to do the following tasks:
1. Copy a file into a different location
2. Delete a file from a location
3. Rename a file

If any of these are possible I would appreciate a point in the right direction.

**Comment by jakemac53** [comment]
Depending on the types of files you want to work with, and whether or not they need to be consumed by other builders, you may want to look at https://pub.dev/documentation/build/latest/build/PostProcessBuilder-class.html.

Otherwise you can do this but only if you can express the move or rename in terms of the `build_extensions` configuration which is pretty limiting. We have an open issue here https://github.com/dart-lang/build/issues/1689 which discusses expanding that in some ways that might make it more feasible but no immediate plans to work on it.

**Comment by FilledStacks** [comment]
@jakemac53 Thank you. Much appreciated for those pointers. 

For more context, It's code that's generated from a builder. I'd like to give a better name and move into a different place after it's been generated.
