### ISSUE TITLE
Help: a generator to modify original annotated class file

### ISSUE THREAD

**Issue by acorn371** [dart-lang/source_gen#582]
How can I use source_gen and Build on an annotated class to modify the original class file ? 
Is it possible to do that ? 
Where can i find an example of it ?
Thanks for any help

**Comment by jakemac53** [comment]
There isn't any support for using generated code in a builder which needs to be ran as a part of the same build - the problem is we create a single program out of all builder imports, so all files must exist before any code is ran, otherwise you get a compile time error.

The easiest solution is to move your libraries that require codegen into a separate package, one that doesn't depend on your builder. That way it has its own build script, and the builder package can depend on that package without issue.
