### ISSUE TITLE
Incorrect (too permissive) regex in CombiningBuilder?

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/source_gen#599]
The `restrictedPatter` seems to handle a literal `.` (dot) incorrectly, it should escape it. The way it is now it means the regex allows any character in that place, including a dot: https://github.com/dart-lang/source_gen/blob/140828cf2bf6747394ad19029cde787c615029d3/source_gen/lib/builder.dart#L90

**Comment by natebosch** [comment]
Luckily this can't surface as an issue because the file names it is filtering were already loaded with a glob that would only have a `.` in that position.

We don't really need the first part of this regex - we could get away with using `.{n}` with the expected number of characters, but it's a bit easier to reason about the way it's written since we _do_ need to filter out stuff that has too much extra in the middle and can't have a regex which matches against only the end of the string.
