### ISSUE TITLE
Add "// dart format width=80" comment in generated code

### ISSUE THREAD

**Issue by munificent** [dart-lang/source_gen#724]
After many years of users asking for it, we are adding support to the formatter for project-wide page width configuration using a surrounding `analysis_options.yaml` file (https://github.com/dart-lang/sdk/issues/56863). However, tools like source_gen don't necessarily have access to (or want to access) IO or know where generated code will end up on disk.

To avoid breaking CI by having the code get generated and formatted at one width and then get formatted to a different width when the user runs `dart format`, we also added support for putting a marker comment in a file to specify an explicit width, like:

```dart
// dart format width=80
```

When this comment is present at the top of the file (before any code, but can be after other comments), then that comment will take precedence and the file will reliably be formatted at that width regardless of any surrounding configuration. So if code generators insert that comment at the top of the code they generate, they don't have to worry about reading the user's configuration.

This issue is requesting that source_gen be updated to add that comment to the code it generates. Since it's just a comment, it's safe to add this at any time. Let me know if you have any questions/feedback and I'll do my best.

**Comment by jakemac53** [comment]
cc @natebosch or @kevmoo could you take this on?

**Comment by natebosch** [comment]
It turns out we have at least 1 project which relies on being able to specify an arbitrarily large width when they format the code in order to have predictable formatting for some particular parts of the generated code where a comment is expected in a certain position

I think it may be feasible to move this so that it inserts the comment during the `formatDartCode` callback, and this would let the use cases that override formatting handle it however they want.

The user visible impact is that the dart format width comment would always be the first line of the file, and it would precede any user defined headers.

@kevmoo @jakemac53 - any concern about that/

**Comment by kevmoo** [comment]
No concerns here, other than general fear about unknown unknowns
